services:
  - type: web
    name: e2ee-chat
    env: node
    region: ohio
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
